version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies"
      - curl -s "https://get.sdkman.io" | bash
      - source "$HOME/.sdkman/bin/sdkman-init.sh"
      - sdk install maven
  pre_build:
    commands:
      - echo "Running pre-build commands"
      - mvn clean install -DskipTests=true
  build:
    commands:
      - echo "Running build commands"
      - mvn package
  post_build:
    commands:
      - echo "Running post-build commands"
      - mv target/*.jar application.jar
      - echo "Creating deployment archive"
      - zip -r deployment.zip application.jar

artifacts:
  files:
    - deployment.zip
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
